spring:
  data:
    mongodb:
#      host: localhost
      host: mongohost
      port: 27017
      database: mydb
#      uri: mongodb://3.35.230.193:27017/mydb

pixabay:
  img-save-dir: C:\Users\ferra\Downloads\saved\
  base-url: https://pixabay.com/api

logging:
  level:
    org:
      springframework:
        web: debug
        data:
          mongodb:
            core:
              MongoTemplate: info
