spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydb

logging:
  level:
    org:
      springframework:
        web: debug
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
